<?php

return [
    'default_components' => [
        ['key' => 'company_header', 'label' => 'Company Header', 'enabled' => true, 'required' => true],
        ['key' => 'invoice_meta', 'label' => 'Invoice Meta', 'enabled' => true, 'required' => false],
        ['key' => 'customer_details', 'label' => 'Customer Details', 'enabled' => true, 'required' => false],
        ['key' => 'sender_details', 'label' => 'Sender Details', 'enabled' => true, 'required' => false],
        ['key' => 'total_summary_box', 'label' => 'Total Summary Box', 'enabled' => true, 'required' => false],
        ['key' => 'line_items', 'label' => 'Line Items Table', 'enabled' => true, 'required' => true],
        ['key' => 'grand_total', 'label' => 'Grand Total', 'enabled' => true, 'required' => false],
        ['key' => 'bank_transfer', 'label' => 'Bank Transfer Information', 'enabled' => true, 'required' => false],
        ['key' => 'transfer_fee_note', 'label' => 'Transfer Fee Note', 'enabled' => true, 'required' => false],
        ['key' => 'invoice_digits_note', 'label' => 'Invoice Digits Note', 'enabled' => true, 'required' => false],
        ['key' => 'unique_number', 'label' => 'Unique Number Indicator', 'enabled' => true, 'required' => false],
    ],

    'currency_locale_map' => [
        'IDR' => ['language' => 'id', 'locale' => 'id-ID'],
        'USD' => ['language' => 'en', 'locale' => 'en-US'],
        'JPY' => ['language' => 'ja', 'locale' => 'ja-JP'],
        'AUD' => ['language' => 'en', 'locale' => 'en-AU'],
        'SGD' => ['language' => 'en', 'locale' => 'en-SG'],
    ],

    'labels' => [
        'en' => [
            'invoice' => 'INVOICE',
            'invoice_date' => 'Invoice Date',
            'invoice_number' => 'Invoice Number',
            'to' => 'To:',
            'item' => 'Item',
            'description' => 'Description',
            'qty' => 'Qty',
            'unit_price' => 'Unit Price',
            'price' => 'Price',
            'amount' => 'Amount',
            'total' => 'Total',
            'grand_total' => 'Grand Total (Tax Incl.)',
            'amount_of_payment' => 'Amount of Payment',
            'total_sum' => 'Total Sum',
            'bank_info' => 'Bank Transfer Information',
            'bank_name' => 'Account Bank',
            'swift_code' => 'SWIFT Code',
            'account_name' => 'Account Name',
            'account_number' => 'Account No',
            'npwp' => 'NPWP',
            'address' => 'Address',
            'phone' => 'Phone',
            'email' => 'E-mail',
            'transfer_fee' => 'Please have your company bear the bank transfer service fees.',
            'payment_instruction' => 'Please make payment to Bank or cash',
            'unique_code_note' => 'Please include last 5 digit of invoice number on the transfer remarks.',
            'unique_code_label' => 'Unique number (for bank transfer)',
            'unique_number_note' => 'Unique number only valid for payment via bank transfer. If payment done by cash, unique number doesn\'t apply.',
            'important_unique_code' => 'Important! Please include unique transfer code',
        ],
        'id' => [
            'invoice' => 'INVOICE',
            'invoice_date' => 'Tanggal Invoice',
            'invoice_number' => 'Nomor Invoice',
            'to' => 'Kepada:',
            'item' => 'Item',
            'description' => 'Deskripsi',
            'qty' => 'Qty',
            'unit_price' => 'Harga Satuan',
            'price' => 'Harga',
            'amount' => 'Jumlah',
            'total' => 'Total',
            'grand_total' => 'Grand Total (Termasuk Pajak)',
            'amount_of_payment' => 'Jumlah Pembayaran',
            'total_sum' => 'Jumlah Total',
            'bank_info' => 'Informasi Transfer Bank',
            'bank_name' => 'Bank',
            'swift_code' => 'Kode SWIFT',
            'account_name' => 'Nama Rekening',
            'account_number' => 'No. Rekening',
            'npwp' => 'NPWP',
            'address' => 'Alamat',
            'phone' => 'Tlp.',
            'email' => 'E-mail',
            'transfer_fee' => 'Biaya jasa transfer bank ditanggung konsumen.',
            'payment_instruction' => 'Silahkan melakukan pembayaran melalui bank atau tunai',
            'unique_code_note' => 'Mohon sertakan 5 digit terakhir nomor invoice pada berita transfer.',
            'unique_code_label' => 'Nomor unik (untuk transfer bank)',
            'unique_number_note' => 'Nomor unik berlaku hanya untuk pembayaran melalui bank. Jika pembayaran secara tunai tidak perlu disertai nomor unik.',
            'important_unique_code' => 'Penting! Mohon sertakan kode unik transfer',
        ],
        'ja' => [
            'invoice' => 'INVOICE',
            'invoice_date' => '請求日',
            'invoice_number' => '請求番号',
            'to' => '御中',
            'item' => '項目',
            'description' => '内容',
            'qty' => '数量',
            'unit_price' => '単価',
            'price' => '金額',
            'amount' => '料金日本円',
            'total' => '合計',
            'grand_total' => '合計金額(税込)',
            'amount_of_payment' => 'お支払い金額',
            'total_sum' => '合計金額',
            'bank_info' => 'お振込先',
            'bank_name' => '銀行名',
            'swift_code' => 'SWIFTコード',
            'account_name' => '口座名義',
            'account_number' => '口座番号',
            'npwp' => 'NPWP',
            'address' => '住所',
            'phone' => '電話',
            'email' => 'メール',
            'transfer_fee' => 'お振込手数料は御社負担にてお願い致します',
            'payment_instruction' => '銀行または現金でお支払いください',
            'unique_code_note' => '振込備考に請求番号の下5桁を記載してください。',
            'unique_code_label' => 'ユニーク番号（銀行振込専用）',
            'unique_number_note' => 'ユニーク番号は銀行振込のみ有効です。現金の場合は不要です。',
            'important_unique_code' => '重要！振込コードを必ず記載してください',
        ],
    ],
];
